# Generated by Django 3.0.5 on 2020-04-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
    ]
