# Generated by Django 3.0.5 on 2020-04-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200411_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
