# Generated by Django 3.0.5 on 2020-04-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200411_0502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sms',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='sms',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
