# Generated by Django 3.0.5 on 2020-04-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200411_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='sms_body',
            field=models.CharField(max_length=500),
        ),
    ]
